Towards doing the Docker builds from within Maven.
- Moved docker setup to src/main/docker
- Dropped resource filtering from for Dockerfile from POM
- Instead added docker-maven-plugin which supports variable replacement in the Dockerfile
- In the Dockerfile, removed lines that download MTAS and data files from GitHub
- Instead added assembly configuration to the docker-maven-plugin (not tested atm; might not work)

diff --git a/src/main/docker/Dockerfile b/src/main/docker/Dockerfile
--- a/src/main/docker/Dockerfile
+++ b/src/main/docker/Dockerfile
@@ -1,7 +1,7 @@
 # Automatically generated Dockerfile 
-# - Build 2017-10-10 06:22
-# - Lucene/Solr version 7.0.1
-# - Mtas release 20171007 
+# - Build @timestamp@
+# - Lucene/Solr version @currentDevelopmentVersion@
+# - Mtas release @project.version@
 #
 
 FROM ubuntu:16.04
@@ -15,11 +15,10 @@ WORKDIR "/root"
 
 RUN mkdir lib 
 
-ADD https://github.com/meertensinstituut/mtas/releases/download/20171007/mtas-7.0.1.jar /root/lib/
-
 RUN apt-get update && apt-get install -y locales lsof software-properties-common python-software-properties apache2 curl subversion && \
     locale-gen en_US.UTF-8 en_US && update-locale LANG=en_US.UTF-8 LANGUAGE=en_US:en
-            
+
+# Include via assembly instead?            
 RUN mathurl=$(curl -s 'http://www.apache.org/dyn/closer.lua/commons/math/binaries/commons-math3-3.6.1-bin.tar.gz' |   grep -o '<strong>[^<]*</strong>' |   sed 's/<[^>]*>//g' |   head -1) && \
     if echo "$mathurl" | grep -q '^.*[^ ].*$'; then \
       curl -f -o /root/lib/commons-math3-3.6.1-bin.tar.gz -O $mathurl || true; \
@@ -31,8 +30,6 @@ RUN mathurl=$(curl -s 'http://www.apache.org/dyn/closer.lua/commons/math/binarie
     fi && \ 
     tar xzf lib/commons-math3-3.6.1-bin.tar.gz -C lib commons-math3-3.6.1/commons-math3-3.6.1.jar --strip-components=1 && \
     rm lib/commons-math3-3.6.1-bin.tar.gz
-    
-RUN svn export https://github.com/meertensinstituut/mtas/trunk/docker/ data 
 
 RUN add-apt-repository -y ppa:webupd8team/java && \
     apt-get update && \
@@ -40,17 +37,17 @@ RUN add-apt-repository -y ppa:webupd8team/java && \
     apt-get install -y oracle-java8-installer && \
     rm -rf /var/lib/apt/lists/*
 
-RUN solrurl=$(curl -s 'http://www.apache.org/dyn/closer.lua/lucene/solr/7.0.1/solr-7.0.1.tgz' |   grep -o '<strong>[^<]*</strong>' |   sed 's/<[^>]*>//g' |   head -1) && \
+RUN solrurl=$(curl -s 'http://www.apache.org/dyn/closer.lua/lucene/solr/@solr.version@/solr-@solr.version@.tgz' |   grep -o '<strong>[^<]*</strong>' |   sed 's/<[^>]*>//g' |   head -1) && \
     if echo "$solrurl" | grep -q '^.*[^ ].*$'; then \
-      curl -f -o /root/solr-7.0.1.tgz -O $solrurl || true; \
+      curl -f -o /root/solr-@solr.version@.tgz -O $solrurl || true; \
     fi && \
-    if [ ! -f /root/solr-7.0.1.tgz ]; then \
-      echo "Solr 7.0.1 not found in mirror, falling back to apache archive"; \ 
-      solrurl="http://archive.apache.org/dist/lucene/solr/7.0.1/solr-7.0.1.tgz"; \
-      curl -f -o /root/solr-7.0.1.tgz -O $solrurl; \ 
+    if [ ! -f /root/solr-@solr.version@.tgz ]; then \
+      echo "Solr @solr.version@ not found in mirror, falling back to apache archive"; \ 
+      solrurl="http://archive.apache.org/dist/lucene/solr/@solr.version@/solr-@solr.version@.tgz"; \
+      curl -f -o /root/solr-@solr.version@.tgz -O $solrurl; \ 
     fi && \    
-    tar xzf solr-7.0.1.tgz solr-7.0.1/bin/install_solr_service.sh --strip-components=2 && \
-    bash ./install_solr_service.sh solr-7.0.1.tgz && rm install_solr_service.sh && rm -rf solr-7.0.1.tgz
+    tar xzf solr-@solr.version@.tgz solr-@solr.version@/bin/install_solr_service.sh --strip-components=2 && \
+    bash ./install_solr_service.sh solr-@solr.version@.tgz && rm install_solr_service.sh && rm -rf solr-@solr.version@.tgz
     
 RUN service apache2 stop && \
     echo "ServerName localhost" | tee /etc/apache2/conf-available/fqdn.conf && \
@@ -74,9 +71,9 @@ RUN service apache2 stop && \
     chmod -R 755 /var/www/html && \
     printf "echo\n" >> /start.sh && \
     printf "echo \"================ Mtas -- Multi Tier Annotation Search =================\"\n" >> /start.sh && \
-    printf "echo \"  Timestamp 2017-10-10 06:22\"\n" >> /start.sh && \
-    printf "echo \"  Lucene/Solr version 7.0.1\"\n" >> /start.sh && \
-    printf "echo \"  Mtas release 20171007\"\n" >> /start.sh && \
+    printf "echo \"  Timestamp @timestamp@\"\n" >> /start.sh && \
+    printf "echo \"  Lucene/Solr version @currentDevelopmentVersion@\"\n" >> /start.sh && \
+    printf "echo \"  Mtas release @currentDevelopmentRelease@\"\n" >> /start.sh && \
     printf "echo \"  See https://meertensinstituut.github.io/mtas/ for more information\"\n" >> /start.sh && \
     printf "echo \"=======================================================================\"\n" >> /start.sh && \
     printf "echo\n" >> /start.sh && \
@@ -85,7 +82,7 @@ RUN service apache2 stop && \
     mkdir demo1 && mkdir demo1/lib && mkdir demo1/conf && \
     echo "name=demo1" > demo1/core.properties && \
     cp lib/commons-math3-3.6.1.jar demo1/lib/ && \
-    cp lib/mtas-7.0.1.jar demo1/lib/ && \
+    cp lib/mtas-@project.version@.jar demo1/lib/ && \
     cp data/solrconfig.xml demo1/conf/ && \
     cp data/schemaBasic.xml demo1/conf/schema.xml && \
     cp -r data/mtas demo1/conf/ && cp data/mtas.xml demo1/conf/ && \
