adjust release mechanism

diff --git a/src/main/docker/Dockerfile b/src/main/docker/Dockerfile
--- a/src/main/docker/Dockerfile
+++ b/src/main/docker/Dockerfile
@@ -1,7 +1,7 @@
 # Automatically generated Dockerfile 
 # - Build ${timestamp}
-# - Lucene/Solr version ${currentDevelopmentVersion}
-# - Mtas release ${currentDevelopmentRelease} 
+# - Lucene/Solr version ${currentLuceneVersion}
+# - Mtas release ${project.version} 
 #
 
 FROM ubuntu:16.04
@@ -15,7 +15,7 @@ WORKDIR "/root"
 
 RUN mkdir lib 
 
-ADD https://github.com/meertensinstituut/mtas/releases/download/${currentDevelopmentRelease}/mtas-${currentDevelopmentVersion}.jar /root/lib/
+ADD https://github.com/meertensinstituut/mtas/releases/download/v${project.version}/mtas-${project.version}.jar /root/lib/
 
 RUN apt-get update && apt-get install -y locales lsof software-properties-common python-software-properties apache2 curl subversion && \
     locale-gen en_US.UTF-8 en_US && update-locale LANG=en_US.UTF-8 LANGUAGE=en_US:en
@@ -40,17 +40,17 @@ RUN add-apt-repository -y ppa:webupd8team/java && \
     apt-get install -y oracle-java8-installer && \
     rm -rf /var/lib/apt/lists/*
 
-RUN solrurl=$(curl -s 'http://www.apache.org/dyn/closer.lua/lucene/solr/${currentDevelopmentVersion}/solr-${currentDevelopmentVersion}.tgz' |   grep -o '<strong>[^<]*</strong>' |   sed 's/<[^>]*>//g' |   head -1) && \
+RUN solrurl=$(curl -s 'http://www.apache.org/dyn/closer.lua/lucene/solr/${currentLuceneVersion}/solr-${currentLuceneVersion}.tgz' |   grep -o '<strong>[^<]*</strong>' |   sed 's/<[^>]*>//g' |   head -1) && \
     if echo "$solrurl" | grep -q '^.*[^ ].*$'; then \
-      curl -f -o /root/solr-${currentDevelopmentVersion}.tgz -O $solrurl || true; \
+      curl -f -o /root/solr-${currentLuceneVersion}.tgz -O $solrurl || true; \
     fi && \
-    if [ ! -f /root/solr-${currentDevelopmentVersion}.tgz ]; then \
-      echo "Solr ${currentDevelopmentVersion} not found in mirror, falling back to apache archive"; \ 
-      solrurl="http://archive.apache.org/dist/lucene/solr/${currentDevelopmentVersion}/solr-${currentDevelopmentVersion}.tgz"; \
-      curl -f -o /root/solr-${currentDevelopmentVersion}.tgz -O $solrurl; \ 
+    if [ ! -f /root/solr-${currentLuceneVersion}.tgz ]; then \
+      echo "Solr ${currentLuceneVersion} not found in mirror, falling back to apache archive"; \ 
+      solrurl="http://archive.apache.org/dist/lucene/solr/${currentLuceneVersion}/solr-${currentLuceneVersion}.tgz"; \
+      curl -f -o /root/solr-${currentLuceneVersion}.tgz -O $solrurl; \ 
     fi && \    
-    tar xzf solr-${currentDevelopmentVersion}.tgz solr-${currentDevelopmentVersion}/bin/install_solr_service.sh --strip-components=2 && \
-    bash ./install_solr_service.sh solr-${currentDevelopmentVersion}.tgz && rm install_solr_service.sh && rm -rf solr-${currentDevelopmentVersion}.tgz
+    tar xzf solr-${currentLuceneVersion}.tgz solr-${currentLuceneVersion}/bin/install_solr_service.sh --strip-components=2 && \
+    bash ./install_solr_service.sh solr-${currentLuceneVersion}.tgz && rm install_solr_service.sh && rm -rf solr-${currentLuceneVersion}.tgz
     
 RUN service apache2 stop && \
     echo "ServerName localhost" | tee /etc/apache2/conf-available/fqdn.conf && \
@@ -75,7 +75,7 @@ RUN service apache2 stop && \
     printf "echo\n" >> /start.sh && \
     printf "echo \"================ Mtas -- Multi Tier Annotation Search =================\"\n" >> /start.sh && \
     printf "echo \"  Timestamp ${timestamp}\"\n" >> /start.sh && \
-    printf "echo \"  Lucene/Solr version ${currentDevelopmentVersion}\"\n" >> /start.sh && \
+    printf "echo \"  Lucene/Solr version ${currentLuceneVersion}\"\n" >> /start.sh && \
     printf "echo \"  Mtas release ${currentDevelopmentRelease}\"\n" >> /start.sh && \
     printf "echo \"  See https://meertensinstituut.github.io/mtas/ for more information\"\n" >> /start.sh && \
     printf "echo \"=======================================================================\"\n" >> /start.sh && \
@@ -85,7 +85,7 @@ RUN service apache2 stop && \
     mkdir demo1 && mkdir demo1/lib && mkdir demo1/conf && \
     echo "name=demo1" > demo1/core.properties && \
     cp lib/commons-math3-3.6.1.jar demo1/lib/ && \
-    cp lib/mtas-${currentDevelopmentVersion}.jar demo1/lib/ && \
+    cp lib/mtas-${currentLuceneVersion}.jar demo1/lib/ && \
     cp data/solrconfig.xml demo1/conf/ && \
     cp data/schemaBasic.xml demo1/conf/schema.xml && \
     cp -r data/mtas demo1/conf/ && cp data/mtas.xml demo1/conf/ && \
